krivine: 
	ocamlc -c krivine.ml
	ocamlc -o krivine krivine.cmo
	./krivine

secd:
	ocamlc -c secd.ml
	ocamlc -o secd secd.cmo
	./secd

.PHONY: all
clean:
	rm -f *.cmo
	rm -f *.cmi
	rm -f krivine
	rm -f secd